import React from "react";
import Image from 'next/image'
import css from '../styles/Home.module.scss'
import TrayIcon from "../components/ui/icons/tray";
import {colors} from "../styles/config/variables";
import Head from 'next/head'
import CardMenu from "../components/ui/icons/card-menu";
import WineBottle from "../components/ui/icons/wine-bottle";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pizza.ico" />
      </Head>
      <main className={css.main}>
        <Image
          src="/landing-pizza-2.jpg"
          alt="pizzeria logo"
          objectFit={'cover'}
          layout={'fill'}
        />
        <section className={css.mainAbsolute}>
          <div className={css.infoGrid}>
            <h1>PIZZERIA TITLE</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type specimen book.
              It has survived not only five centuries, but also the leap into electronic typesetting, remaining
              essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
              Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including
              versions of Lorem Ipsum.</p>
            <div>Social</div>
          </div>
          <div className={css.iconsContainer}>
            <div className={css.iconItem}>
              <CardMenu size={64} color={colors.whiteColor} />
              <p>MENU</p>
            </div>
            <div className={css.iconItem}>
              <TrayIcon size={64} color={colors.whiteColor} />
              <p>SPECIALS</p>
            </div>
            <div className={css.iconItem}>
              <WineBottle size={64} color={colors.whiteColor} />
              <p>DRINKS</p>
            </div>
          </div>
        </section>
      </main>

      <footer className={css.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={css.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
